FROM python:latest
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /task_management_api
COPY requirements.txt /task_management_api/
RUN pip install -r requirements.txt
COPY . /task_management_api/