services:
  localhost:
    container_name: mysql_con
    image: mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gokeptonedb
      - MYSQL_USER= root
      - MYSQL_PASSWORD= ''
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  phpmyadmin:
    container_name: phpmyadmin_con
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - localhost

  django_project:
    container_name: django_con
    image: django-img
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    volumes:
      - .:/task_management_api
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      localhost:
        condition: service_healthy